# Zentrale IP-Adresse des i-soft Geräts
default_config:

input_text:
  isoft_ip:
    name: i-soft IP-Adresse
    initial: "192.168.2.21"
    min: 7
    max: 15
    mode: text

homeassistant:
  packages: !include_dir_named packages

# Einbindung der nativen YAML-Integrationen
rest: !include rest.yaml
rest_command: !include rest_commands.yaml
script: !include scripts.yaml

# Virtuelles Gerät verankern
template:
  - sensor:
      - name: "i-soft PRO Status"
        unique_id: isoft_pro_status_clean
        state: "Online"
        icon: mdi:water-softener
        
